// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lazyledgerapp/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetPayForMessageRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPayForMessageRequest) Reset()         { *m = QueryGetPayForMessageRequest{} }
func (m *QueryGetPayForMessageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPayForMessageRequest) ProtoMessage()    {}
func (*QueryGetPayForMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e248d35cd763ec8, []int{0}
}
func (m *QueryGetPayForMessageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPayForMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPayForMessageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPayForMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPayForMessageRequest.Merge(m, src)
}
func (m *QueryGetPayForMessageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPayForMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPayForMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPayForMessageRequest proto.InternalMessageInfo

func (m *QueryGetPayForMessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetPayForMessageResponse struct {
	PayForMessage *PayForMessage `protobuf:"bytes,1,opt,name=PayForMessage,proto3" json:"PayForMessage,omitempty"`
}

func (m *QueryGetPayForMessageResponse) Reset()         { *m = QueryGetPayForMessageResponse{} }
func (m *QueryGetPayForMessageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPayForMessageResponse) ProtoMessage()    {}
func (*QueryGetPayForMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e248d35cd763ec8, []int{1}
}
func (m *QueryGetPayForMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPayForMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPayForMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPayForMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPayForMessageResponse.Merge(m, src)
}
func (m *QueryGetPayForMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPayForMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPayForMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPayForMessageResponse proto.InternalMessageInfo

func (m *QueryGetPayForMessageResponse) GetPayForMessage() *PayForMessage {
	if m != nil {
		return m.PayForMessage
	}
	return nil
}

type QueryAllPayForMessageRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPayForMessageRequest) Reset()         { *m = QueryAllPayForMessageRequest{} }
func (m *QueryAllPayForMessageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPayForMessageRequest) ProtoMessage()    {}
func (*QueryAllPayForMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e248d35cd763ec8, []int{2}
}
func (m *QueryAllPayForMessageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPayForMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPayForMessageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPayForMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPayForMessageRequest.Merge(m, src)
}
func (m *QueryAllPayForMessageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPayForMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPayForMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPayForMessageRequest proto.InternalMessageInfo

func (m *QueryAllPayForMessageRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPayForMessageResponse struct {
	PayForMessage []*PayForMessage    `protobuf:"bytes,1,rep,name=PayForMessage,proto3" json:"PayForMessage,omitempty"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPayForMessageResponse) Reset()         { *m = QueryAllPayForMessageResponse{} }
func (m *QueryAllPayForMessageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPayForMessageResponse) ProtoMessage()    {}
func (*QueryAllPayForMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e248d35cd763ec8, []int{3}
}
func (m *QueryAllPayForMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPayForMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPayForMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPayForMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPayForMessageResponse.Merge(m, src)
}
func (m *QueryAllPayForMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPayForMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPayForMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPayForMessageResponse proto.InternalMessageInfo

func (m *QueryAllPayForMessageResponse) GetPayForMessage() []*PayForMessage {
	if m != nil {
		return m.PayForMessage
	}
	return nil
}

func (m *QueryAllPayForMessageResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetPayForMessageRequest)(nil), "lazyledger.lazyledgerapp.lazyledgerapp.QueryGetPayForMessageRequest")
	proto.RegisterType((*QueryGetPayForMessageResponse)(nil), "lazyledger.lazyledgerapp.lazyledgerapp.QueryGetPayForMessageResponse")
	proto.RegisterType((*QueryAllPayForMessageRequest)(nil), "lazyledger.lazyledgerapp.lazyledgerapp.QueryAllPayForMessageRequest")
	proto.RegisterType((*QueryAllPayForMessageResponse)(nil), "lazyledger.lazyledgerapp.lazyledgerapp.QueryAllPayForMessageResponse")
}

func init() { proto.RegisterFile("lazyledgerapp/query.proto", fileDescriptor_5e248d35cd763ec8) }

var fileDescriptor_5e248d35cd763ec8 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x49, 0xac, 0xaa,
	0xcc, 0x49, 0x4d, 0x49, 0x4f, 0x2d, 0x4a, 0x2c, 0x28, 0xd0, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x43, 0x48, 0xe9, 0xa1, 0xa8, 0x42, 0xe5, 0x49, 0xc9,
	0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97,
	0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x4c, 0x91, 0xd2, 0x4a, 0xce, 0x2f, 0xce, 0xcd, 0x2f,
	0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0x85, 0x18, 0xaf, 0x5f, 0x66, 0x98, 0x94, 0x5a, 0x92, 0x68, 0xa8,
	0x5f, 0x90, 0x98, 0x9e, 0x99, 0x07, 0x56, 0x0c, 0x55, 0xab, 0x88, 0xea, 0x98, 0x80, 0xc4, 0x4a,
	0xb7, 0xfc, 0x22, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x88, 0x12, 0x25, 0x3d, 0x2e, 0x99,
	0x40, 0x90, 0x21, 0xee, 0xa9, 0x25, 0x28, 0xd2, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x4a,
	0x35, 0x5c, 0xb2, 0x38, 0xd4, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x45, 0x73, 0xf1, 0xa2,
	0x48, 0x80, 0xf5, 0x72, 0x1b, 0x99, 0xea, 0x11, 0xe7, 0x7b, 0x3d, 0x54, 0x53, 0x51, 0xcd, 0x52,
	0x4a, 0x83, 0xba, 0xd6, 0x31, 0x27, 0x07, 0xab, 0x6b, 0xdd, 0xb8, 0xb8, 0x10, 0x81, 0x00, 0xb5,
	0x59, 0x4d, 0x0f, 0x12, 0x62, 0x7a, 0xa0, 0x10, 0xd3, 0x83, 0x44, 0x08, 0x34, 0xc4, 0xf4, 0x02,
	0x10, 0x7a, 0x83, 0x90, 0x74, 0x2a, 0x1d, 0x65, 0x84, 0x7a, 0x13, 0xd3, 0x22, 0xdc, 0xde, 0x64,
	0xa6, 0x96, 0x37, 0x85, 0xdc, 0x51, 0xbc, 0xc1, 0x04, 0xf6, 0x86, 0x3a, 0x41, 0x6f, 0x40, 0x5c,
	0x86, 0xec, 0x0f, 0xa3, 0xd3, 0xcc, 0x5c, 0xac, 0x60, 0x7f, 0x08, 0x3d, 0x60, 0x44, 0x73, 0xb0,
	0x90, 0x0b, 0xb1, 0x4e, 0xc5, 0x97, 0x3e, 0xa4, 0x5c, 0x29, 0x34, 0x05, 0xe2, 0x68, 0x25, 0xa7,
	0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xd9, 0x08, 0x59, 0xe9, 0x23, 0x74, 0xe9, 0xa3, 0xa6, 0x5e, 0x3c,
	0x69, 0x59, 0xbf, 0x3a, 0x33, 0xa5, 0x56, 0xe8, 0x1e, 0x23, 0x97, 0x00, 0x8a, 0xb0, 0x63, 0x4e,
	0x0e, 0x89, 0xbe, 0xc4, 0x91, 0xae, 0x48, 0xf4, 0x25, 0xae, 0x44, 0xa3, 0x64, 0x0b, 0xf6, 0xa5,
	0xb9, 0x90, 0x29, 0x59, 0xbe, 0x74, 0x0a, 0x39, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6,
	0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39,
	0x86, 0x28, 0xab, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xec, 0x46, 0xeb,
	0x82, 0x4c, 0xab, 0x40, 0x33, 0xbd, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x5c, 0x10, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x75, 0x0f, 0x4c, 0xba, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	PayForMessage(ctx context.Context, in *QueryGetPayForMessageRequest, opts ...grpc.CallOption) (*QueryGetPayForMessageResponse, error)
	PayForMessageAll(ctx context.Context, in *QueryAllPayForMessageRequest, opts ...grpc.CallOption) (*QueryAllPayForMessageResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PayForMessage(ctx context.Context, in *QueryGetPayForMessageRequest, opts ...grpc.CallOption) (*QueryGetPayForMessageResponse, error) {
	out := new(QueryGetPayForMessageResponse)
	err := c.cc.Invoke(ctx, "/lazyledger.lazyledgerapp.lazyledgerapp.Query/PayForMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PayForMessageAll(ctx context.Context, in *QueryAllPayForMessageRequest, opts ...grpc.CallOption) (*QueryAllPayForMessageResponse, error) {
	out := new(QueryAllPayForMessageResponse)
	err := c.cc.Invoke(ctx, "/lazyledger.lazyledgerapp.lazyledgerapp.Query/PayForMessageAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	PayForMessage(context.Context, *QueryGetPayForMessageRequest) (*QueryGetPayForMessageResponse, error)
	PayForMessageAll(context.Context, *QueryAllPayForMessageRequest) (*QueryAllPayForMessageResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PayForMessage(ctx context.Context, req *QueryGetPayForMessageRequest) (*QueryGetPayForMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayForMessage not implemented")
}
func (*UnimplementedQueryServer) PayForMessageAll(ctx context.Context, req *QueryAllPayForMessageRequest) (*QueryAllPayForMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayForMessageAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PayForMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPayForMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PayForMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lazyledger.lazyledgerapp.lazyledgerapp.Query/PayForMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PayForMessage(ctx, req.(*QueryGetPayForMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PayForMessageAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPayForMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PayForMessageAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lazyledger.lazyledgerapp.lazyledgerapp.Query/PayForMessageAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PayForMessageAll(ctx, req.(*QueryAllPayForMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lazyledger.lazyledgerapp.lazyledgerapp.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayForMessage",
			Handler:    _Query_PayForMessage_Handler,
		},
		{
			MethodName: "PayForMessageAll",
			Handler:    _Query_PayForMessageAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lazyledgerapp/query.proto",
}

func (m *QueryGetPayForMessageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPayForMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPayForMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPayForMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPayForMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPayForMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PayForMessage != nil {
		{
			size, err := m.PayForMessage.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPayForMessageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPayForMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPayForMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPayForMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPayForMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPayForMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PayForMessage) > 0 {
		for iNdEx := len(m.PayForMessage) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PayForMessage[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetPayForMessageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPayForMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PayForMessage != nil {
		l = m.PayForMessage.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPayForMessageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPayForMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PayForMessage) > 0 {
		for _, e := range m.PayForMessage {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetPayForMessageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPayForMessageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPayForMessageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPayForMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPayForMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPayForMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayForMessage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PayForMessage == nil {
				m.PayForMessage = &PayForMessage{}
			}
			if err := m.PayForMessage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPayForMessageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPayForMessageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPayForMessageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPayForMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPayForMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPayForMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayForMessage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayForMessage = append(m.PayForMessage, &PayForMessage{})
			if err := m.PayForMessage[len(m.PayForMessage)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
